export const FALLBACK_ROOMMATE_QUESTIONS = [
  {
    code: "cleanliness_priority",
    step_number: 1,
    display_order: 1,
    title: "Orden y limpieza",
    prompt: "¿Qué nivel de orden necesitas para estar a gusto en casa?",
    helper_text: "Nos ayuda a encontrar ritmos de convivencia compatibles.",
    input_type: "scale",
    category: "lifestyle",
    is_required: true,
    options: [
      { value: 1, label: "Flexible" },
      { value: 3, label: "Equilibrado" },
      { value: 5, label: "Muy ordenado" },
    ],
  },
  {
    code: "sleep_schedule",
    step_number: 2,
    display_order: 2,
    title: "Horario habitual",
    prompt: "¿Cómo suele ser tu ritmo entre semana?",
    helper_text: "Piensa en tus guardias, estudio y descanso.",
    input_type: "single_choice",
    category: "lifestyle",
    is_required: true,
    options: [
      { value: "early_bird", label: "Madrugador/a" },
      { value: "balanced", label: "Bastante equilibrado" },
      { value: "night_owl", label: "Nocturno/a" },
    ],
  },
  {
    code: "weekday_vibe",
    step_number: 3,
    display_order: 3,
    title: "Plan entre semana",
    prompt: "Después del hospital o la facultad, ¿qué ambiente prefieres en casa?",
    helper_text: null,
    input_type: "single_choice",
    category: "lifestyle",
    is_required: true,
    options: [
      { value: "quiet", label: "Tranquilo y silencioso" },
      { value: "balanced", label: "Algo de charla pero con calma" },
      { value: "social", label: "Con vida y planes" },
    ],
  },
  {
    code: "shared_spaces",
    step_number: 4,
    display_order: 4,
    title: "Espacios compartidos",
    prompt: "¿Qué cosas te importan más en una convivencia?",
    helper_text: "Puedes marcar varias.",
    input_type: "multi_choice",
    category: "lifestyle",
    is_required: true,
    options: [
      { value: "clean_kitchen", label: "Cocina cuidada" },
      { value: "shared_meals", label: "Compartir alguna comida" },
      { value: "quiet_nights", label: "Noches tranquilas" },
      { value: "guest_rules", label: "Normas claras con visitas" },
      { value: "study_respect", label: "Respeto a estudio o descanso" },
    ],
  },
  {
    code: "weekend_plan",
    step_number: 5,
    display_order: 5,
    title: "Fin de semana",
    prompt: "¿Qué plan encaja más contigo cuando libras?",
    helper_text: null,
    input_type: "single_choice",
    category: "profile",
    is_required: true,
    options: [
      { value: "stay_in", label: "Casa, descanso y recados" },
      { value: "mixed", label: "Un poco de todo" },
      { value: "go_out", label: "Salir y hacer planes" },
    ],
  },
  {
    code: "roommate_goal",
    step_number: 6,
    display_order: 6,
    title: "Lo que buscas",
    prompt: "¿Qué te gustaría encontrar en tu próximo compi de piso?",
    helper_text: null,
    input_type: "text",
    category: "search",
    is_required: true,
    options: [],
  },
];
