import React from "react";
import {
  Plus,
  PlusCircle,
  WarningCircle,
  Archive,
  ArrowLeft,
  ArrowDown,
  ArrowCircleDown,
  ArrowRight,
  ArrowUUpLeft,
  ArrowUp,
  Prohibit,
  ChartBar,
  Basketball,
  Book,
  Briefcase,
  PaintBrush,
  Bug,
  Lightbulb,
  Buildings,
  Coffee,
  Calendar,
  CalendarBlank,
  CalendarCheck,
  Phone,
  Camera,
  Money,
  ChatDots,
  ChatCircleDots,
  ChatCircle,
  Chats,
  Check,
  CheckCircle,
  Checks,
  CaretLeft,
  CaretDown,
  CaretRight,
  CaretUp,
  Clipboard,
  X,
  XCircle,
  CloudArrowDown,
  Compass,
  NotePencil,
  FileText,
  DownloadSimple,
  Globe,
  DotsThree,
  SignOut,
  EyeSlash,
  Eye,
  Funnel,
  Fingerprint,
  Lightning,
  Flask,
  FolderOpen,
  Folder,
  SoccerBall,
  Gift,
  GridFour,
  Heart,
  House,
  Hourglass,
  Image,
  Images,
  Info,
  Link,
  ListBullets,
  MapPin,
  LockSimple,
  InstagramLogo,
  Envelope,
  EnvelopeOpen,
  MapTrifold,
  Stethoscope,
  FirstAidKit,
  Megaphone,
  List,
  Microphone,
  Moon,
  NavigationArrow,
  Bell,
  BellSlash,
  ArrowSquareOut,
  SlidersHorizontal,
  PaperPlaneTilt,
  PawPrint,
  Pencil,
  Users,
  User,
  UserPlus,
  UserCircle,
  Minus,
  ForkKnife,
  Medal,
  FloppyDisk,
  GraduationCap,
  MagnifyingGlass,
  ShieldCheck,
  Sparkle,
  Star,
  ArrowsLeftRight,
  ArrowsDownUp,
  TennisBall,
  TextT,
  ThumbsUp,
  Clock,
  Timer,
  Trash,
  TrendDown,
  TrendUp,
  Wallet,
  Warning,
  Wine,
  Bookmark,
  Wrench,
  Scissors,
  Lifebuoy,
  Question,
  Newspaper,
  Pulse,
  // OJO: en phosphor-react-native 3.x el icono "circle" se exporta SOLO como
  // `CircleIcon` (no tiene el alias plano `Circle` que sí tienen los demás).
  // Importarlo como `Circle` daba `undefined` y hacía que el fallback de abajo
  // reventara con "Element type is invalid". Lo aliaseamos aquí.
  CircleIcon as Circle,
} from "phosphor-react-native";

// ============================================================================
// Icon — wrapper único de iconos de la app sobre Phosphor (phosphor-react-native).
//
// REGLA DEL PROYECTO: todos los iconos de la app se renderizan con Phosphor a
// través de este componente. No importes `@expo/vector-icons` (Ionicons, etc.)
// ni otra librería de iconos. Si necesitas un icono que no está mapeado, añade
// la entrada correspondiente a IONICON_TO_PHOSPHOR (y, si aplica, a FILLED).
//
// Mantiene la API por nombre (compatible con el uso previo de Ionicons), por lo
// que también funcionan los `name={variable}` que se resuelven en runtime.
// ============================================================================

// Mapa nombre-de-Ionicons -> componente Phosphor. Las variantes `-outline` /
// `-sharp` de Ionicons se mapean al mismo icono Phosphor (el "peso" se controla
// con la prop `weight`, ver FILLED más abajo).
const IONICON_TO_PHOSPHOR = {
  add: Plus,
  "add-circle-outline": PlusCircle,
  "alert-circle": WarningCircle,
  "alert-circle-outline": WarningCircle,
  "archive-outline": Archive,
  "arrow-back": ArrowLeft,
  "arrow-back-outline": ArrowLeft,
  "arrow-down": ArrowDown,
  "arrow-down-circle": ArrowCircleDown,
  "arrow-forward": ArrowRight,
  "arrow-forward-outline": ArrowRight,
  "arrow-undo": ArrowUUpLeft,
  "arrow-up": ArrowUp,
  "ban-outline": Prohibit,
  "bar-chart": ChartBar,
  basketball: Basketball,
  book: Book,
  "book-outline": Book,
  bookmark: Bookmark,
  "bookmark-outline": Bookmark,
  briefcase: Briefcase,
  "briefcase-outline": Briefcase,
  build: Wrench,
  "build-outline": Wrench,
  brush: PaintBrush,
  "brush-outline": PaintBrush,
  "bug-outline": Bug,
  "bulb-outline": Lightbulb,
  business: Buildings,
  "business-outline": Buildings,
  "cafe-outline": Coffee,
  calendar: Calendar,
  "calendar-clear-outline": CalendarBlank,
  "calendar-outline": Calendar,
  call: Phone,
  "call-outline": Phone,
  camera: Camera,
  "camera-outline": Camera,
  cash: Money,
  "cash-outline": Money,
  "chatbox-ellipses-outline": ChatDots,
  "chatbubble-ellipses-outline": ChatCircleDots,
  "chatbubble-outline": ChatCircle,
  chatbubbles: Chats,
  "chatbubbles-outline": Chats,
  checkmark: Check,
  "checkmark-circle": CheckCircle,
  "checkmark-circle-outline": CheckCircle,
  "checkmark-done": Checks,
  "chevron-back": CaretLeft,
  "chevron-down": CaretDown,
  "chevron-forward": CaretRight,
  "chevron-up": CaretUp,
  "clipboard-outline": Clipboard,
  close: X,
  "close-circle": XCircle,
  "cloud-download-outline": CloudArrowDown,
  compass: Compass,
  "compass-outline": Compass,
  cut: Scissors,
  "cut-outline": Scissors,
  create: NotePencil,
  "create-outline": NotePencil,
  "document-text": FileText,
  "document-text-outline": FileText,
  "download-outline": DownloadSimple,
  "earth-outline": Globe,
  "ellipsis-horizontal": DotsThree,
  "exit-outline": SignOut,
  "eye-off-outline": EyeSlash,
  "eye-outline": Eye,
  filter: Funnel,
  "filter-outline": Funnel,
  "finger-print": Fingerprint,
  "flash-outline": Lightning,
  flask: Flask,
  "flask-outline": Flask,
  "folder-open-outline": FolderOpen,
  "folder-outline": Folder,
  football: SoccerBall,
  "gift-outline": Gift,
  globe: Globe,
  "grid-outline": GridFour,
  heart: Heart,
  "heart-circle": Heart,
  "heart-outline": Heart,
  "help-buoy": Lifebuoy,
  "help-buoy-outline": Lifebuoy,
  "help-circle": Question,
  "help-circle-outline": Question,
  home: House,
  "home-outline": House,
  "hourglass-outline": Hourglass,
  "image-outline": Image,
  images: Images,
  "images-outline": Images,
  "information-circle": Info,
  "information-circle-outline": Info,
  link: Link,
  list: ListBullets,
  "list-outline": ListBullets,
  location: MapPin,
  "location-outline": MapPin,
  "lock-closed": LockSimple,
  "lock-closed-outline": LockSimple,
  "logo-instagram": InstagramLogo,
  mail: Envelope,
  "mail-open": EnvelopeOpen,
  "mail-outline": Envelope,
  "mail-unread": Envelope,
  map: MapTrifold,
  "map-outline": MapTrifold,
  medical: Stethoscope,
  "medical-outline": Stethoscope,
  medkit: FirstAidKit,
  "medkit-outline": FirstAidKit,
  megaphone: Megaphone,
  menu: List,
  mic: Microphone,
  "mic-outline": Microphone,
  moon: Moon,
  "moon-outline": Moon,
  "navigate-outline": NavigationArrow,
  newspaper: Newspaper,
  "newspaper-outline": Newspaper,
  notifications: Bell,
  "notifications-off-outline": BellSlash,
  "notifications-outline": Bell,
  "open-outline": ArrowSquareOut,
  "options-outline": SlidersHorizontal,
  "paper-plane-outline": PaperPlaneTilt,
  "paw-outline": PawPrint,
  pencil: Pencil,
  "pencil-outline": Pencil,
  people: Users,
  "people-circle-outline": Users,
  "people-outline": Users,
  person: User,
  "person-add-outline": UserPlus,
  "person-circle": UserCircle,
  "person-circle-outline": UserCircle,
  "person-outline": User,
  pulse: Pulse,
  "pulse-outline": Pulse,
  remove: Minus,
  "reorder-three-outline": List,
  "restaurant-outline": ForkKnife,
  "ribbon-outline": Medal,
  "save-outline": FloppyDisk,
  school: GraduationCap,
  "school-outline": GraduationCap,
  search: MagnifyingGlass,
  "search-outline": MagnifyingGlass,
  send: PaperPlaneTilt,
  "shield-checkmark-outline": ShieldCheck,
  sparkles: Sparkle,
  "sparkles-outline": Sparkle,
  star: Star,
  "star-outline": Star,
  "stats-chart-outline": ChartBar,
  "swap-horizontal": ArrowsLeftRight,
  "swap-vertical": ArrowsDownUp,
  tennisball: TennisBall,
  "tennisball-outline": TennisBall,
  text: TextT,
  "thumbs-up": ThumbsUp,
  "thumbs-up-outline": ThumbsUp,
  time: Clock,
  "time-outline": Clock,
  "timer-outline": Timer,
  today: CalendarCheck,
  trash: Trash,
  "trash-outline": Trash,
  "trending-down": TrendDown,
  "trending-up": TrendUp,
  "trending-up-outline": TrendUp,
  "wallet-outline": Wallet,
  warning: Warning,
  "warning-outline": Warning,
  wine: Wine,
  "wine-outline": Wine,
};

// Nombres de Ionicons "sólidos" (sin `-outline`) cuyo relleno tiene significado
// (estados activos: like, favorito, avatar, campana). Para estos el peso por
// defecto es "fill"; el resto usa "regular" (look de línea). Siempre se puede
// forzar con la prop `weight`.
const FILLED = new Set([
  "heart",
  "heart-circle",
  "star",
  "thumbs-up",
  "checkmark-circle",
  "person",
  "person-circle",
  "notifications",
]);

/**
 * Icono de la app (Phosphor por debajo).
 *
 * @param {object} props
 * @param {string} props.name - nombre estilo Ionicons (ver IONICON_TO_PHOSPHOR)
 * @param {number} [props.size=24]
 * @param {string} [props.color]
 * @param {'thin'|'light'|'regular'|'bold'|'fill'|'duotone'} [props.weight]
 */
export const Icon = ({ name, size = 24, color, weight, ...rest }) => {
  const Cmp = IONICON_TO_PHOSPHOR[name];

  if (!Cmp) {
    if (__DEV__) {
      // eslint-disable-next-line no-console
      console.warn(`[Icon] sin mapeo Phosphor para "${name}" — usando fallback.`);
    }
    // Fallback defensivo: si por cualquier motivo (mapeo ausente, o un cambio en
    // phosphor-react-native que retire un alias) no hay componente, NUNCA debemos
    // renderizar `undefined` porque React revienta con "Element type is invalid"
    // y tumba toda la pantalla. Preferimos un círculo o, en el peor caso, nada.
    return Circle
      ? <Circle size={size} color={color} weight="regular" {...rest} />
      : null;
  }

  const resolvedWeight = weight || (FILLED.has(name) ? "fill" : "regular");
  return <Cmp size={size} color={color} weight={resolvedWeight} {...rest} />;
};

export default Icon;
